#!/bin/bash

# Set reference genome, genome indexes, junction and annotation database directory paths
REF=$HOME/BIOC281/Classes/2/STARindex_2p/PARYMSK_100bp
FTQ=$HOME/BIOC281/Classes/2/reads

# Set parameters
CmmnPrms="--runThreadN 4 --outSJfilterReads Unique --outFilterType BySJout --outSAMunmapped Within \
--outSAMattributes NH HI AS nM NM MD jM jI XS MC ch --outFilterMultimapNmax 20 --outFilterMismatchNmax 999 --alignIntronMin 20 \
--outFilterMismatchNoverReadLmax 0.04 --alignIntronMax 1000000 --alignMatesGapMax 1000000 \
--alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --sjdbScore 1"
AdtlPrms="--outSAMtype BAM SortedByCoordinate --outBAMcompression 10 --limitBAMsortRAM 57000000000 \
--quantMode TranscriptomeSAM GeneCounts --quantTranscriptomeBAMcompression 10 --outSAMstrandField intronMotif"

# Set directories for run
export OWD=`pwd`
export SCR=$HOME/scratch_male_2p
export STR=$SCR/STARun
export RDIR=$STR/reads

# create scratch and read directory 
mkdir -p $RDIR
## create STR scratch directory and subdirectories
mkdir -p $STR/male_2p/

# Copy processed reads to local scratch space "\$RDIR" and decompress-- can be used if skewer has already been used for 1p mapping.
cp -a $FTQ/male-*pair* $RDIR
cd $RDIR
gzip -d $RDIR/*.gz
 
## run 2nd pass STAR alignment
STAR $CmmnPrms $AdtlPrms --genomeDir $REF --outFileNamePrefix $STR/male_2p/male.2p. \
--readFilesIn $RDIR/male-trimmed-pair1.fastq $RDIR/male-trimmed-pair2.fastq
#
## Create index for remapped bam file
samtools index $STR/male_2p/male.2p.Aligned.sortedByCoord.out.bam

# delete reads in $SCR to save space. The reads are no longer needed.
rm -rf $RDIR/*

# compress files that are needed for downstream analysis
find $STR -type f \( -name "*.out" -o -name "*.tab" -o -name "*.sjdb" -o -name "*.results" \) | xargs gzip -9

# Cleanup and Copy back all important files
if [ ! -d $OWD/STAResults ];
then 
mkdir -p $OWD/STAResults
fi

# Copy back important files
cp -a $STR/male_2p $OWD/STAResults/

# Remove scratch directory
rm -rf $SCR
exit 0
