#!/bin/bash

## Set reference genome, genome indexes, junction and annotation database directory paths
REF=$GROUP_HOME/BIOC281/Classes/2/RefSeq_Oct2020/GenomeIndex/STARIndex/100bp_PRMSK
GFA=$REF/hg38.RefSeq.mini.PARYhMSK.ERCC.fa
ANN=$GROUP_HOME/BIOC281/Classes/2/RefSeq_Oct2020/Annotation/hg38.refGene.ERCC.gtf
FTQ=$GROUP_HOME/BIOC281/Classes/2/fastq/male

## Set parameters, see https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf
## to see explanation for the paramters used
CmmnPrms="--runThreadN 4 --outSJfilterReads Unique --outFilterType BySJout --outSAMunmapped Within \
--outSAMattributes NH HI AS nM NM MD jM jI XS MC ch --outFilterMultimapNmax 20 --outFilterMismatchNmax 999 --alignIntronMin 20 \
--outFilterMismatchNoverReadLmax 0.04 --alignIntronMax 1000000 --alignMatesGapMax 1000000 \
--alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --sjdbScore 1"
AdtlPrms="--outSAMtype BAM SortedByCoordinate --outBAMcompression 10 --limitBAMsortRAM 57000000000 \
--quantMode TranscriptomeSAM GeneCounts --quantTranscriptomeBAMcompression 10 --outSAMstrandField intronMotif"

## Define directory structure for run
export OWD=`pwd`
export SCR=$GROUP_HOME/scratch_male
export STR=$SCR/STARun
export RDIR=$SCR/reads

## create scratch run directory and read directory 
mkdir -p $RDIR

## concatenate read files if they are split into multiple files
cat $FTQ/*R1*.fastq.gz > $SCR/male_R1.fastq.gz
cat $FTQ/*R2*.fastq.gz > $SCR/male_R2.fastq.gz

## decompress read files
gzip -d $SCR/*.fastq.gz

## Start skewer to trim reads for quality of base calls and remove adapter sequences at 3' ends
## While STAR employs soft clipping to remove ends of reads that do not align, best practice is to
## NOT leave this to chance and to "hard clip" the sequences before alignment
cd $RDIR

## If Truseq Illumina adapters (obsolete) were used to prepare the library then use the following adapter sequences
#skewer -x AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG \
#-y AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT \
#-t 4 -q 21 -l 31 -n -u -o male -f sanger --quiet $SCR/male_R1.fastq $SCR/male_R2.fastq

## If Nextera Illumina primers were used to prepare the library then use the following adapter sequences
skewer -x CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG \
-y CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT \
-t 4 -q 21 -l 31 -n -u -o male -f sanger --quiet $SCR/male_R1.fastq $SCR/male_R2.fastq

## If custom CZBiohub IDT primers (Index=12bp) were used to prepare the library then use the following adapter sequences
#skewer -x CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG \
#-y CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT \
#-t 4 -q 21 -l 31 -n -u -o male -f sanger --quiet $SCR/male_R1.fastq $SCR/male_R2.fastq

## Start STAR alignment
mkdir -p $STR/male_1p
cd $STR

STAR $CmmnPrms $AdtlPrms --genomeDir $REF --outFileNamePrefix $STR/male_1p/male.1p. \
--readFilesIn $RDIR/male-trimmed-pair1.fastq $RDIR/male-trimmed-pair2.fastq
 
## Create index for the mapped bam file; this will make it easier to browse the mapped bam file in IGV browser
samtools index $STR/male_1p/male.1p.Aligned.sortedByCoord.out.bam

## Compress skwer-processed reads to save space.
gzip --best $RDIR/*

## Compress files that are needed for downstream analysis
find $STR -type f \( -name "*.out" -o -name "*.tab" -o -name "*.sjdb" -o -name "*.results" \) | xargs gzip -9

## Cleanup and copy back all important files
if [ ! -d $OWD/reads ];
then 
mkdir -p $OWD/{reads,STAResults}
fi

## Copy back important files
cp -a $STR/male_1p $OWD/STAResults/
cp -a $RDIR/* $OWD/reads/

## Remove scratch directory
rm -rf $SCR
exit 0
